USE TechShop;

--Task 4: Subqueries and Their Types

--1.Find customers who have not placed any orders

SELECT C.CustomerID, C.FirstName, C.LastName, C.Email
FROM Customers C
WHERE NOT EXISTS (SELECT 1 FROM Orders O WHERE O.CustomerID = C.CustomerID);

--2.Find total number of products available

SELECT COUNT(*) AS TotalProducts FROM Products;

--3.Calculate total revenue generated by TechShop

SELECT SUM(TotalAmount) AS TotalRevenue FROM Orders;

--4.Find the average quantity ordered for products in a category (User input)

DECLARE @CategoryName VARCHAR(100) = 'Laptops';

SELECT AVG(OD.Quantity) AS AvgQuantityOrdered
FROM OrderDetails OD
JOIN Products P ON OD.ProductID = P.ProductID
JOIN Categories C ON P.CategoryID = C.CategoryID
WHERE C.CategoryName = @CategoryName;

--5.Find total revenue generated by a specific customer (User input)

DECLARE @CustomerID INT = 1;

SELECT SUM(O.TotalAmount) AS CustomerRevenue
FROM Orders O
WHERE O.CustomerID = @CustomerID;

--6.Find customers who placed the most orders

SELECT TOP 1 C.FirstName, C.LastName, COUNT(O.OrderID) AS TotalOrders
FROM Customers C
JOIN Orders O ON C.CustomerID = O.CustomerID
GROUP BY C.CustomerID, C.FirstName, C.LastName
ORDER BY TotalOrders DESC;

--7.Find the most popular product category

SELECT TOP 1 C.CategoryName, SUM(OD.Quantity) AS TotalOrdered
FROM OrderDetails OD
JOIN Products P ON OD.ProductID = P.ProductID
JOIN Categories C ON P.CategoryID = C.CategoryID
GROUP BY C.CategoryName
ORDER BY TotalOrdered DESC;

--8.Find the customer who spent the most money

SELECT TOP 1 C.FirstName, C.LastName, SUM(O.TotalAmount) AS TotalSpending
FROM Orders O
JOIN Customers C ON O.CustomerID = C.CustomerID
GROUP BY C.CustomerID, C.FirstName, C.LastName
ORDER BY TotalSpending DESC;

--9.Calculate the average order value for all customers

SELECT AVG(O.TotalAmount) AS AverageOrderValue FROM Orders O;

--10.Find the total number of orders placed by each customer

SELECT C.CustomerID, C.FirstName, C.LastName, COUNT(O.OrderID) AS OrderCount
FROM Customers C
LEFT JOIN Orders O ON C.CustomerID = O.CustomerID
GROUP BY C.CustomerID, C.FirstName, C.LastName;